### ISSUE TITLE
Installation problem - compilation

### ISSUE THREAD

**Issue by lucasrct** [asoroa/ukb#10]
When I try to compile the program after ./configure --with-boost-include=/usr/include/ I get this error

$ make
3.2.7.g7f3a305
g++ -c -O2 -Wall -Wno-deprecated -D UKB_SERVER -o globalVars.o -I /usr/include/ globalVars.cc
g++ -O2 -Wall -Wno-deprecated -D UKB_SERVER -o ukb_walkandprint ukb_walkandprint.cc common.o globalVars.o ukbServer.o configFile.o fileElem.o kbGraph.o kbGraph_common.o kbGraph_v16.o disambGraph.o csentence.o wdict.o walkandprint.o -I /usr/include/  -L/usr/include/boost/ -lboost_program_options -lboost_system -lboost_filesystem -lboost_random -lpthread
fileElem.o: In function `ukb::File_elem::fill(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) `:
fileElem.cc:(.text+0x364): undefined reference to `boost::filesystem::path::m_normalize() `
collect2: error: ld returned 1 exit status
Makefile:43: recipe for target 'ukb_walkandprint' failed
make: *** [ukb_walkandprint] Error 1

My boost version is 1.65

**Comment by asoroa** [comment]
Hi, 
the problem seems to be that the build system doesn't find the boost libraries (not the header files, but the .so files). Try specifying the library path in configure:  

```
./configure --with-boost-lib=/path/to/boost/libraries  --with-boost-include=/path/to/boost/include
```

if you are still having problems, you can try downloading boost yourself. See `src/INSTALL`

**Comment by lucasrct** [comment]
I was specifying the wrong library path. Now it compiled. Thanks.
