### ISSUE TITLE
collocations or MWEs

### ISSUE THREAD

**Issue by arademaker** [asoroa/ukb#12]
I am trying to understand what is the current support for MWE (or collocations) detection in the script from https://github.com/asoroa/ukb/tree/master/src. I am assuming that only MWE already identified would be disambiguated, right? The code here has any support to detect MWE presented in the KB?

**Comment by asoroa** [comment]
There is no code related to MWE detection in ukb. If you want to process MWEs you need to pass them explicitly in the input context (using underscores, i.e., "new_york#n#id#1", etc). See examples, for instance, in https://github.com/asoroa/ukb/tree/master/src/dotest/input/ctx.txt
