### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by arademaker** [asoroa/ukb#13]
I guess you may have a presentation about the general idea of UKB right? Can you share the slides? I am trying to prepare something to my students but I realize that maybe you have already a good examples that shows the ideia.

**Comment by asoroa** [comment]
I have an old presentation, I hope it is useful
[ukb_pres.pdf](https://github.com/asoroa/ukb/files/8416456/ukb_pres.pdf)

**Comment by arademaker** [comment]
thank you
