### ISSUE TITLE
fake_id

### ISSUE THREAD

**Issue by arademaker** [asoroa/ukb#15]
https://github.com/asoroa/ukb/blob/7f3a305054972a00eb55f52909caf585e0e00551/src/README#L282-L283

is `fake_id` something that needs to be put literally as the string "fake_id" or any other id would work? Why did you use the same `fake_id` for the last two fake elements? Is it a mistake in the example or do we really need to use the same id for all fake elements introduced in the context?

**Comment by asoroa** [comment]
anything would do.

**Comment by arademaker** [comment]
Sorry for the silly questions, but I do want to avoid any misunderstanding. In the example, the two extra fake words need to have the same ID or they can be different?
