### ISSUE TITLE
UKB on Mac OS

### ISSUE THREAD

**Issue by pilehvar** [asoroa/ukb#2]
Hi,

Is it possible to compile UKB on Mac?

After installing boost and while compiling the code, I get the following error:

./wdict.h:173:28: error: field of type 'value_type' (aka '__wrap_iter<const_pointer>') has private constructor
                        freq_const_iterator() : m_current(0) {}
                                                ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:1239:31: note: declared private here
    _LIBCPP_INLINE_VISIBILITY __wrap_iter(iterator_type __x) _NOEXCEPT : __i(__x) {}
                              ^
In file included from kbGraph_v16.cc:4:
./wdict.h:206:16: error: no member named 'tr1' in namespace 'std'
                typedef std::tr1::unordered_map<std::string, wdict_rhs_t > wdict_t;
                        ~~~~~^
./wdict.h:206:34: error: expected member name or ';' after declaration specifiers
                typedef std::tr1::unordered_map<std::string, wdict_rhs_t > wdict_t;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./wdict.h:207:16: error: no member named 'tr1' in namespace 'std'
                typedef std::tr1::unordered_map<Kb_vertex_t, winvdict_rhs_t > winvdict_t;
                        ~~~~~^
./wdict.h:207:34: error: expected member name or ';' after declaration specifiers
                typedef std::tr1::unordered_map<Kb_vertex_t, winvdict_rhs_t > winvdict_t;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
./wdict.h:216:9: error: unknown type name 'wdict_t'; did you mean 'wint_t'?
                const wdict_t & wdict() const  { return m_wdict; };

Thanks,
Taher

**Comment by luigi-asprino** [comment]
Hi, 

I'm also trying to compile UKB on MAC.
I've installed boost_1_54_0 with the following commands:
$ ./bootstrap.sh --with-libraries=graph,system,filesystem,program_options,regex,random
$ ./b2 install --layout=system

I've configured UKB 
$ ./configure --with-boost-include=/usr/local/include/

but the make command returned:
$ make
g++ -c -O3 -Wall -Wno-deprecated -o common.o -I /usr/local/include common.cc
2.1.32.g0d582e1
g++ -c -O3 -Wall -Wno-deprecated -o globalVars.o -I /usr/local/include globalVars.cc
g++ -c -O3 -Wall -Wno-deprecated -o configFile.o -I /usr/local/include configFile.cc
g++ -c -O3 -Wall -Wno-deprecated -o fileElem.o -I /usr/local/include fileElem.cc
g++ -c -O3 -Wall -Wno-deprecated -o kbGraph.o -I /usr/local/include kbGraph.cc
g++ -c -O3 -Wall -Wno-deprecated -o kbGraph_common.o -I /usr/local/include kbGraph_common.cc
g++ -c -O3 -Wall -Wno-deprecated -o kbGraph_v16.o -I /usr/local/include kbGraph_v16.cc
In file included from kbGraph_v16.cc:4:
./wdict.h:172:28: error: field of type 'value_type' (aka '__wrap_iter<const ukb::winvdict_item_t *>') has private constructor
                        freq_const_iterator() : m_current(0) {}
                                                ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iterator:1239:31: note: declared private here
    _LIBCPP_INLINE_VISIBILITY __wrap_iter(iterator_type __x) _NOEXCEPT : __i(__x) {}
                              ^
1 error generated.
make: **\* [kbGraph_v16.o] Error 1

**Any suggestions?**

Thanks,
Luigi

**Comment by asoroa** [comment]
Hi,

(sorry for the late reply. Usually I follow the issues via the ukb mailing list at http://groups.google.com/group/ukblist)

Unfortunately I don't have any mac computer to try ukb, and thus currently it only compiles on unix/linux machines. Sorry about that.

best,

aitor
