### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rahmanjalayer** [asoroa/ukb#5]
hi.
All of the Ixa Tools have install instruction, like NER and POS as follow:
https://github.com/ixa-ehu/ixa-pipe-nerc
https://github.com/ixa-ehu/ixa-pipe-pos

 but ukb doesn't have.
I don't know how to install and use it?
can anyone help me to install it like another tools?

**Comment by asoroa** [comment]
Hi,

instructions for installing ukb are in src/INSTALL. Please note that, unlike ixa-pipes, ukb is written in C++, and thus requires you to compile the source files to obtain the executables.
Alternatively, you can get pre-compiled binaries here: http://ixa2.si.ehu.es/ukb/ukb_3.0.tgz

best,
aitor

**Comment by rahmanjalayer** [comment]
thanks for your answer. I have got pre-compiled binaries. but how to use it?for example in tokenizer i can use this command to execute:
cat Sample.txt | java-jar ixa-pipe-tok-2.0.0-exec.jar tok -l en
and it gives me a naf file. how to use this tool and what is its input and output?






On Monday, August 28, 2017, 8:08:12 PM GMT+4:30, asoroa <notifications@github.com> wrote:


Hi,

instructions for installing ukb are in src/INSTALL. Please note that, unlike ixa-pipes, ukb is written in C++, and thus requires you to compile the source files to obtain the executables.
Alternatively, you can get pre-compiled binaries here: http://ixa2.si.ehu.es/ukb/ukb_3.0.tgz

best,
aitor

**Comment by asoroa** [comment]
Hi,

to use ukb as a ixa-pipes module you need the naf_ukb script at https://github.com/asoroa/naf_ukb 
The script contains documentation, including installation instructions and usage examples. Hopefully they will be clear enough, but please don't hesitate to ask if you have further questions.

best,
aitor

**Comment by rahmanjalayer** [comment]
thank you. it was very useful for me and it worked.but I've run follow sentence in ixa-demo( http://ixa2.si.ehu.es/nrdemo/demo.php ) :
"Porsche family buys back 10 pc stake from Qatar"
for instance, the term "family" has several external references:   
   - 
   -  <term id="t2" type="open" lemma="family" pos="N" morphofeat="NN">
   -  <span>
   -  <target id="w2"/>
   -  </span>
   -  <externalReferences>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08078020-n" confidence="0.352583"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-07970406-n" confidence="0.264529"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-10236304-n" confidence="0.110265"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-07997703-n" confidence="0.0906662"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-07970721-n" confidence="0.0709183"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08107499-n" confidence="0.0432138"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08227916-n" confidence="0.0353143"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08246302-n" confidence="0.0325098"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-08078020-n" confidence="0.17639068"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-08107499-n" confidence="0.14130068"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-07970721-n" confidence="0.1564572"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-07970406-n" confidence="0.2473728"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-10236304-n" confidence="0.14290242"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-07997703-n" confidence="0.13557623"/>
   -  <externalRef resource="WordNet-3.0" reference="ili-30-08227916-n"/>
   -  </externalReferences>
   -  </term>

but in my file it has just resource="wn30g.bin64" and doesn't have wordnet-3.0. like follow:   
   -    

   -  <externalRef resource="wn30g.bin64" reference="ili-30-08078020-n" confidence="0.352583"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-07970406-n" confidence="0.264529"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-10236304-n" confidence="0.110265"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-07997703-n" confidence="0.0906662"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-07970721-n" confidence="0.0709183"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08107499-n" confidence="0.0432138"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08227916-n" confidence="0.0353143"/>
   -  <externalRef resource="wn30g.bin64" reference="ili-30-08246302-n" 

how to add both of the wordnet3.0 and wn30g.bin64 to output naf file?thanks in advance.

On Tuesday, August 29, 2017, 1:31:52 PM GMT+4:30, asoroa <notifications@github.com> wrote:


Hi,

to use ukb as a ixa-pipes module you need the naf_ukb script at https://github.com/asoroa/naf_ukb
The script contains documentation, including installation instructions and usage examples. Hopefully they will be clear enough, but please don't hesitate to ask if you have further questions.

best,
aitor

**Comment by asoroa** [comment]
Hi,
this is because the ixa-demo runs 2  wsd modules: ukb, which creates the 'wn30g.bin64' links, and svm_wsd (at https://github.com/cltl/svm_wsd) which creates the Wordnet-3.0 links. You should contact the developers of svm_wsd to integrate it into your workflow.

best,
aitor

**Comment by rahmanjalayer** [comment]
thank you very much.
