### ISSUE TITLE
regarding out of the KB words

### ISSUE THREAD

**Issue by arademaker** [asoroa/ukb#6]
> Words in the context must have an entry on the dictionary. Otherwise, the
system won't be able to relate the context word to KB concepts, and the word
will not be used for WSD purposes. Therefore, contexts are usually formed by
content-words, i.e., prepositions, pronouns etc. are usually discarded.

The performance can be affected by words out of the KB if we leave than in the input file?

**Comment by asoroa** [comment]
the performance is affected just by the time spent filtering out the words (a hash lookup)
